title: Joel # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Graduate student studting applied statistics at the University of Kansas online<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/joel-k-160aa9162/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-54516992-1 # your Google Analytics tracking ID here
